### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by edbizarro** [SocialiteProviders/Providers#307] opened 2019-04-30 15:49 UTC
https://socialiteproviders.netlify.com is down

![Page Not Found](https://user-images.githubusercontent.com/84926/56975051-65b8bf80-6b46-11e9-92f2-24d0e6ef67c4.png)

**Comment by m1guelpf** [comment] 2019-05-02 06:51
Would appreciate a PR to the documentation site

**Comment by sinkcup** [comment] 2019-05-06 04:42
PR https://github.com/SocialiteProviders/Documentation/pull/48

duplicate of https://github.com/SocialiteProviders/Documentation/issues/47

**Comment by m1guelpf** [comment] 2019-05-06 10:28
Fixed

**Closed by m1guelpf** 2019-05-06 10:28 UTC
Labels: bug
